### ISSUE TITLE
compiler error

### ISSUE THREAD

**Issue by tianyj** [culvertsoft/mgen#1]
Hi:
  when I use Mgen,I have something error: 

![qq 20141231171007](https://cloud.githubusercontent.com/assets/4436762/5586622/e7f17908-910f-11e4-8ccf-040ac555a28e.jpg)

the Mgen dir : E:\mgen-0.1, and I have set the environmental variables(MGEN_INSTALL_PATH) ,and add it to path

project.xml and module file are

``` <Project>
  <Sources>
    <Source>model.xml</Source>
  </Sources>
  <Generator name="Java">
    <output_path>src/main/java</output_path>
    <classregistry_path>com.catpaw</classregistry_path>
      <class_path>se.culvertsoft.mgen.javapack.generator.JavaGenerator</class_path>
  </Generator>
</Project>

<Module>
  <Types>
    <Apple>
      <weight type="float32"/>
      <name type="string" />
    </Apple>
  </Types>
</Module>
```

how can to resolve the error?

thanks!

**Comment by GiGurra** [comment]
You seem to have done everything correct. Can you confirm that:
- MGEN_INSTALL_PATH points to E:/mgen-0.1
- There exists a file E:/mgen-0.1/jars/mgen-javagenerator.jar

to check on windows:
- 'echo %MGEN_INSTALL_PATH%' -> E:\mgen-0.1

or linux:
- 'echo $MGEN_INSTALL_PATH' -> /home/.../mgen-0.1

Can you also tell me what command you use to call the compiler?

For example, if environment variables don't work (for whatever reason), you can try passing plugin paths to the compiler as an argument:
- mgen myproject.xml -plugin_paths="E:/mgen-0.1/jars"

**Comment by tianyj** [comment]
I checked MGEN_INSTALL_PATH , it's correct, but it don't work.
my command  : 
`mgen project.xml.`
Now I use: 
`mgen myproject.xml -plugin_paths="E:/mgen-0.1/jars"`
It compiled successfully , Maybe the  MGEN_INSTALL_PATH does not work.
Thanks,and Happy New Year!

**Comment by GiGurra** [comment]
I just tested downloading 0.1 on my computer and MGEN_INSTALL_PATH  works for me :/ (using english win7 64bit java7 64bit).
Also checked the code and not seeing anything wrong right now..

Sry I cannot explain why the environment variable is not working for you :(.
In addition to setting MGEN_INSTALL_PATH to E:/mgen-0.1, can you try setting MGEN_PLUGIN_PATH to E:/mgen-0.1/jars ?

---

What if you try writing a java application like:

```
public static void main(String[] args) {
    System.out.println(System.getenv("MGEN_INSTALL_PATH"));
}
```

**Comment by tianyj** [comment]
the console print: null( System.out.println(System.getenv("MGEN_INSTALL_PATH")); ),Maybe the environment variable does not work.
I check my environment variables,it is setted correctly:

![20141231171305](https://cloud.githubusercontent.com/assets/4436762/5605095/3914ef70-9423-11e4-80f6-cc7a29085d04.jpg)

**Comment by GiGurra** [comment]
Interesting!
Maybe it has to do with some localization/language issue.

Or some permission/user issue for your jvm?
Can you try this:

```
    System.out.println("Envirionment Variables:");
    for (java.util.Map.Entry<String, String> e : System.getenv().entrySet()) {
        System.out.println("   " + e.getKey() + " = " + e.getValue());
    }
```

What variables can your jvm see?

Are you running mgen on the same user name you set the environment variable?

**Comment by tianyj** [comment]
I find reason that the environment variable of MGEN_INSTALL_PATH does not work.
It need to restart computer.
After restart,the MGEN_INSTALL_PATH works!
I didn't shutdown computer for over a mouth, maybe it needs rest.:smile:
Thanks!
